---
- name: deploy new version of the project to the server
  hosts: all
  remote_user: buildout
  tasks:
    - name: "Checkout correct version from github"
      git:
        accept_hostkey: yes
        dest: /srv/{{ project_name }}
        repo: ssh://git@github.com/KW1993/ICON_D2.git
        version: "master"

    - name: "Stop docker"
      shell:
        cmd: "docker-compose stop"
        chdir: /srv/{{ project_name }}

    - name: "Build docker"
      shell:
        cmd: "docker-compose build"
        chdir: /srv/{{ project_name }}

    - name: "UPLOAD ICON D2 PRECP"
      cron:
        name: "ICON D2 task"
        minute: "48"
        hour: "*/6"
        job: "cd /srv/{{ project_name }} && docker-compose run --rm script python3 scripts/uploadICON.py"
